apiVersion: v1
kind: Pod
metadata:
  name: group2-spark-shuffle
  labels:
    run: group2-spark-shuffle
    spark-version: 2.4.0
spec:
  serviceAccountName: spark
  volumes:
    - name: temp-volume
      hostPath:
        path: '/tmp/spark-local' # change this path according to your cluster configuration.
  containers:
    - name: group2-spark-shuffle
      # This is an official image that is built
      # from the dockerfiles/shuffle directory
      # in the spark distribution.
      image: jaeyeun97/spark-shuffle
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: '/tmp/spark-local'
          name: temp-volume
          # more volumes can be mounted here.
          # The spark job must be configured to use these
          # mounts using the configuration:
          #   spark.kubernetes.shuffle.dir=<mount-1>,<mount-2>,...
