apiVersion: v1
kind: Service
metadata:
  name: group2-custom-master
  labels:
    run: group2-custom-master
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: shibal
  selector:
    run: group2-custom-master
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: group2-custom-master
spec:
  selector:
    matchLabels:
      run: group2-custom-master
  replicas: 1
  template:
    metadata:
      labels:
        run: group2-custom-master
    spec:
      containers:
      - name: wordcount-master
        image: jaeyeun97/wordcount-master:latest
        ports:
        - containerPort: 8000
        env:
        - name: AWS_ACCESS_KEY_ID
          value: {aws_access_key_id}
        - name: AWS_SECRET_ACCESS_KEY
          value: {aws_secret_access_key}
        - name: AWS_DEFAULT_REGION
          value: eu-west-2
        - name: FILE_URL
          value: {file_url}
        args: ['{file_url}']
