apiVersion: v1
kind: Service
metadata:
  name: group2-custom-master
  labels:
    run: group2-custom-master
spec:
  type: ClusterIP 
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: shibal
  selector:
    run: group2-custom-master
